general:
  debug: true
  write_history: false
  # optional:
  # history_retention_policy: RETENTION_POLICY_NAME
  cron: '*/15 * * * *'
darksky:
  key: DARKSKY_KEY
  units: auto
  language: en
  locations:
    - longitude: DARKSKY_LONGITUDE
      latitude: DARKSKY_LATITUDE
      name: FRIENDLY_LOCATION_NAME
influxdb:
  host: INFLUXDB_HOST
  database: INFLUXDB_DATABASE
  username: INFLUXDB_USERNAME
  password: INFLUXDB_PASSWORD